import { Item } from 'types/Item';

export const materials: Item[] = [
  {
    id: '170',
    name: 'リンゴ',
    description:
      'ハイラルでスタンダードな果物。そのまま食べてもいいし、料理に使えば効果もアップする。',
    locations: ['ハイラル平原', '東ハテール'],
    heartsRecoverable: 1,
    cookingEffect: '特になし',
  },
  {
    id: '171',
    name: 'ヤシの実',
    description: '海辺のヤシの木に実る素ルーツ。特別な効果はないが料理に使うとハートを回復させる効果がある。',
    locations: ['東ハテール', 'ゲルド砂漠'],
    heartsRecoverable: 1,
    cookingEffect: '特になし',
  },
  {
    id: '172',
    name: 'イチゴ',
    description: '雪の降る寒い地方で実るフルーツ。甘酸っぱい味が特徴で特に効果はないが、料理にもよく使われる。',
    locations: ['ゲルド高地', 'へブラ山脈'],
    heartsRecoverable: 0.5,
    cookingEffect: '特になし',
  },
  {
    id: '173',
    name: 'マックスドリアン',
    description: '強烈なにおいが特徴のフルーツの王様。強力な回復力があり、料理に使うとハートが限界を大きく超えて回復する。',
    locations: ['西ハテール', 'フィローネ草原'],
    heartsRecoverable: 3,
    cookingEffect: 'MAXハート',
  },
  {
    id: '174',
    name: 'ヒンヤリメロン',
    description: '砂漠でも育つ特殊なフルーツ。ジューシーなカニ国は体温を下げる効果があり、料理に使うと暑さに耐える効果を発揮する。',
    locations: ['ゲルド砂漠', 'フィローネ草原'],
    heartsRecoverable: 0.5,
    cookingEffect: '暑さガード',
  },
  {
    id: '175',
    name: 'ポカポカ草の実',
    description: '生で食べるとピリピリする実。料理に使うと体が暖まり、寒いところでも耐えられるようになる。',
    locations: ['ゲルド砂漠', 'タバンタ辺境'],
    heartsRecoverable: 0.5,
    cookingEffect: '寒さガード',
  },
  {
    id: '176',
    name: 'ビリビリフルーツ',
    description: 'ゲルド砂漠のサボテンに実るフルーツ。甘い実には絶縁成分が豊富に含まれており、料理に使うと電気の攻撃に強くなる効果がある。',
    locations: ['ゲルド砂漠', 'ゲルド高地'],
    heartsRecoverable: 0.5,
    cookingEffect: 'エレキガード',
  },
  {
    id: '177',
    name: 'ゴーゴーハスの実',
    description: '水辺に咲いているハスの実。水中深くは巡らせた根から集まった栄養は、料理に使うと移動速度が上がる校歌として現れる。',
    locations: ['ラネール湿原', 'ラネール大水源'],
    heartsRecoverable: 0.5,
    cookingEffect: '移動力アップ',
  },
  {
    id: '178',
    name: 'ツルギバナナ',
    description: '主にフィローネ地方の熱帯林に実るフルーツ。皮に包まれた果肉には筋力増強効果があるとされ、料理にすると攻撃力が増す料理ができる。',
    locations: ['フィローネ地方'],
    heartsRecoverable: 0.5,
    cookingEffect: '攻撃アップ',
  },
  {
    id: '179',
    name: 'ハイラルダケ',
    description: 'ハイラルの森を代表するキノコ。木のそばに生えることが多く、食べるとハート回復の効果がある。',
    locations: ['ハイラル平原', '西ハテール'],
    heartsRecoverable: 0.5,
    cookingEffect: '特になし',
  }
];
