import type { Item } from 'types/Item';

export const materials: Item[] = [
  {
    id: '203',
    category: 'materials',
    name: 'リンゴ',
    description:
      '太古の昔から 人々に食べられている果物 そのまま食べてもいいし 料理の材料に使えば 効果もアップする',
    locations: ['ハイラル平原', 'オルディーン峡谷'],
    fuseAttackPower: 1,
    heartsRecoverable: 1,
  },
  {
    id: '204',
    category: 'materials',
    name: '金のリンゴ',
    description:
      '普通のリンゴに混じって 時折見つかる神秘的な 輝きを放つ果物 食べると味わった事のない 甘みが口の中いっぱいに広がる',
    locations: ['ハイラル全域'],
    fuseAttackPower: 1,
    heartsRecoverable: 1.5,
    cookingEffect: '効果時間アップ +00:20',
  },
  {
    id: '205',
    category: 'materials',
    name: 'ヤシの実',
    description:
      '海辺のヤシの木に実るフルーツ 特別な効果はないが料理に使うと ハートを回復させる効果がある',
    locations: ['東ハテール', 'ゲルド砂漠'],
    fuseAttackPower: 1,
    heartsRecoverable: 1,
  },
  {
    id: '206',
    category: 'materials',
    name: 'イチゴ',
    description:
      '雪の降る寒い地方で実るフルーツ 甘酸っぱい味が特徴で 特別な効果はないが 料理にもよく使われる',
    locations: ['ヘブラ山脈', 'ゲルド高地'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
  },
  {
    id: '207',
    category: 'materials',
    name: 'ハイラルトマト',
    description:
      '寒冷地から 温暖な気候まで 幅広く分布する果実 栄養たっぷりで 近年注目されている 料理に使うと ハートの回復量が増える',
    locations: ['東ハテール', '西ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 1,
  },
  {
    id: '208',
    category: 'materials',
    name: 'ヒンヤリメロン',
    description:
      '砂漠でも育つ特殊なフルーツ ジューシーな果肉には体温を下げる効果があり 料理に使うと 暑さに耐える効果を発揮する',
    locations: ['ゲルド砂漠'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '暑さガード',
  },
  {
    id: '209',
    category: 'materials',
    name: 'ポカポカ草の実',
    description:
      '生で食べるとピリピリする実 料理に使うと 体が暖まり 寒いところでも耐えられるようになる',
    locations: ['ハイラル丘陵', 'オルディン峡谷'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '寒さガード',
  },
  {
    id: '210',
    category: 'materials',
    name: 'ビリビリフルーツ',
    description:
      'ゲルド砂漠のサボテンに実るフルーツ 甘い実には 絶縁成分が豊富に含まれており 料理に使うと 電気の攻撃に強くなる効果がある',
    locations: ['ゲルド砂漠'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: 'エレキガード',
  },
  {
    id: '211',
    category: 'materials',
    name: 'ゴーゴーハスの実',
    description:
      '水辺に咲いているハスの実 水中深く張り巡らせた根から集まった栄養は 料理に使うと 移動速度が上がる効果として現れる',
    locations: ['ラネール大水源', 'ラネール湿原'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '移動力アップ',
  },
  {
    id: '212',
    category: 'materials',
    name: 'ツルギバナナ',
    description:
      '主にフィローネ地方の 熱帯林に実るフルーツ 皮に包まれた果肉には 筋力増増効果があるとされ 調理すると 攻撃力が増す料理ができる',
    locations: ['フィローネ地方', 'ヘブラ山脈'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '攻撃力アップ',
  },
  {
    id: '213',
    category: 'materials',
    name: '火炎の実',
    description:
      '破裂すると熱を発する実 熱で筋肉を活性化する 成分を含むため 料理にして食す事で 高温時に強力な攻撃を繰り出せるようになる',
    locations: ['ハイラル平原', 'オルディン峡谷'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
    cookingEffect: '高温時炎攻撃',
  },
  {
    id: '214',
    category: 'materials',
    name: '冷気の実',
    description:
      '破裂すると冷気を発する実 冷やすと普段使わない 筋繊維を強化する作用があり 料理して食べれば 寒冷時に強力な攻撃を繰り出せるようになる',
    locations: ['ヘブラ山脈', 'ゲルド高地'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
    cookingEffect: '寒冷時冷気攻撃',
  },
  {
    id: '215',
    category: 'materials',
    name: '水の実',
    description:
      '中に高圧の水をため込んだ木の実 手足の動きを滑らかにする成分によって 料理して食べると 速く泳げるようになる',
    locations: ['ラネール大水源', '西ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
    cookingEffect: '泳ぎスピードアップ',
  },
  {
    id: '216',
    category: 'materials',
    name: '電気の実',
    description:
      '破裂すると電気を発する実 雷鳴に反応して 筋力を刺激する成分を含むため 料理にして食すと 雷雨下で強力な攻撃を繰り出せるようになる',
    locations: ['東ハテール', 'ゲルド砂漠'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
    cookingEffect: '雷雨時電気攻撃',
  },
  {
    id: '217',
    category: 'materials',
    name: 'カガヤキの実',
    description:
      '強い光をため込んだ木の実 破裂すると周囲にまばゆい閃光を放ち 光を受けた魔物の目をくらます事ができる',
    locations: ['ハイラル丘陵', 'アッカレ高原'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
  },
  {
    id: '218',
    category: 'materials',
    name: 'ハイラルダケ',
    description:
      'ハイラルの森を代表するキノコ 木のそばに生える事が多く 食べるとハート回復の効果がある',
    locations: ['ハイラル全域'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
  },
  {
    id: '219',
    category: 'materials',
    name: 'ソラダケ',
    description:
      '空島の木の根元に生える ポピュラーなキノコ 食べるとハート回復の効果がある',
    locations: ['ハイラル空島'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
  },
  {
    id: '220',
    category: 'materials',
    name: 'ガッツダケ',
    description:
      'めったに取れない黄色いキノコ 料理するとがんばりゲージの最大値が増える というとても貴重な効果を発揮する',
    locations: ['北タバンタ空諸島', '北ハテール空諸島'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: 'MAXがんばり',
  },
  {
    id: '221',
    category: 'materials',
    name: 'ガンバリダケ',
    description:
      '大地のエネルギーをたくさんため込んだ 栄養満点のキノコ 料理に使うと がんばりが回復する効果を得られる',
    locations: ['ラネール大水源', '西ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: 'がんばり回復',
  },
  {
    id: '222',
    category: 'materials',
    name: 'マックストリュフ',
    description:
      'かなり貴重なキノコの一種 土の中で育ち 強い香りがある 料理に使うと ハート全回復と 最大値を増やす効果をもつ',
    locations: ['ハイラル平原', '西ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 2,
    cookingEffect: 'MAXハート',
  },
  {
    id: '223',
    category: 'materials',
    name: '大マックストリュフ',
    description:
      '誰にも発見されず 大きく育ったマックストリュフ 蓄えられた栄養も豊富で 料理に使うと ハートが全回復し さらに最大値を大きく増やす',
    locations: ['東ハテール', 'ゲルド砂漠'],
    fuseAttackPower: 1,
    heartsRecoverable: 3,
    cookingEffect: 'MAXハート',
  },
  {
    id: '224',
    category: 'materials',
    name: 'ヒンヤリダケ',
    description:
      '雪山の針葉樹の根元によく生える 触るとヒンヤリしていて 料理に使うと 砂漠の暑さにも耐える事ができるようになる',
    locations: ['ゲルド高地', 'ヘブラ山脈'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '暑さガード',
  },
  {
    id: '225',
    category: 'materials',
    name: 'ポカポカダケ',
    description:
      '主に気温の高い地域に生える真っ赤なキノコ 見た目通り炎の力を宿しており 料理に使うと 寒い雪山でも耐えられる効果が発揮される',
    locations: ['オルディン峡谷', 'ゲルド高地'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '寒さガード',
  },
  {
    id: '226',
    category: 'materials',
    name: 'ビリビリダケ',
    description:
      'ゲルド地方でよく見かけられるキノコ 傘の部分に 絶縁成分が豊富に含まれている 料理に使うと 電撃に耐性を得られる',
    locations: ['ゲルド砂漠', 'ラネール湿原'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: 'エレキガード',
  },
  {
    id: '227',
    category: 'materials',
    name: 'ゴーゴーダケ',
    description:
      '天井や切り立った崖にむりやり生えるキノコ どこにでも生える生命力がすごい 料理に使うと移動力が向上する効果がある',
    locations: ['ゲルド高地', 'タバンタ辺境'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '移動力アップ',
  },
  {
    id: '228',
    category: 'materials',
    name: 'ツルギダケ',
    description:
      '剣で斬りつけたようなヒビが特徴のキノコ 料理に使うと 傘の裏のひだに含まれる成分により 闘争心が向上し 攻撃力が増すと言われる',
    locations: ['ハイラル大森林', 'タバンタ辺境'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '攻撃力アップ',
  },
  {
    id: '229',
    category: 'materials',
    name: 'ヨロイダケ',
    description:
      '傘がとても硬く発達したキノコ その傘に含まれる成分は 調理して食べると 体幹を強化する効能があり 防御力が増す',
    locations: ['東ハテール', '西ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '防御アップ',
  },
  {
    id: '230',
    category: 'materials',
    name: 'シノビダケ',
    description:
      '夜になると静かに光る 不思議なキノコ 料理に使うと 傘に含まれる成分で集中力が高まり 物音を立てずに行動できるようになる',
    locations: ['アッカレ高原', '西ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '静かさアップ',
  },
  {
    id: '231',
    category: 'materials',
    name: 'アカリダケ',
    description:
      '洞窟に生える 光る酵素を含有したキノコ 料理に使うと その発光成分で 食した者の 身体が ぼんやり光る効能を得られる',
    locations: ['ハイラルの洞窟'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '発光',
  },
  {
    id: '232',
    category: 'materials',
    name: 'ケムリダケ',
    description:
      '非常に細かい胞子を蓄えたキノコ 刺激を受けると 一面に胞子の粉塵を撒き散らす 味はとても苦く 食べられたものではない',
    locations: ['ハイラルの地底'],
    fuseAttackPower: 1,
  },
  {
    id: '233',
    category: 'materials',
    name: 'ハイラル草',
    description:
      'はるか昔から 今の姿をしていたとされるハーブ 生命力に満ちあふれており 料理に使うと ハートを回復させる効果がある',
    locations: ['ハイラル平原', 'ハイラル丘陵'],
    fuseAttackPower: 1,
    heartsRecoverable: 1,
  },
  {
    id: '234',
    category: 'materials',
    name: 'ガンバリ草',
    description:
      '冷涼な気候を好む 根元のふくらんだ野草 そこに体力や持久力を強化する成分が含まれ 料理に使うとがんばり回復する効果が現れる',
    locations: ['始まりの空島', '雷鳴の島'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: 'がんばり回復',
  },
  {
    id: '235',
    category: 'materials',
    name: 'マックスラディッシュ',
    description:
      '日当たりの良い草原に自生する珍しいカブ 料理に使うとハートが全回復し さらに最大値を増やす効果がある',
    locations: ['ラネール空諸島', '南ラネール空諸島'],
    fuseAttackPower: 1,
    heartsRecoverable: 2.5,
    cookingEffect: 'MAXハート',
  },
  {
    id: '236',
    category: 'materials',
    name: '大マックスラディッシュ',
    description:
      '限界を超えて大きく育ったマックスラディッシュ 滋養強壮成分がとても豊富で 料理に使うと ハートが全回復し さらに最大値を大きく増やす',
    locations: ['雷鳴の島', '北ハテール空諸島'],
    fuseAttackPower: 1,
    heartsRecoverable: 4,
    cookingEffect: 'MAXハート',
  },
  {
    id: '237',
    category: 'materials',
    name: 'ヒンヤリハーブ',
    description:
      'ヘブラやゲルドの標高の高い山地で見かけられる 薬草の一種 葉に身体を冷やす成分を持っており 料理に使うと 耐暑効果を得る事ができる',
    locations: ['ヘブラ山脈', 'タバンタ辺境'],
    fuseAttackPower: 1,
    cookingEffect: '暑さガード',
  },
  {
    id: '238',
    category: 'materials',
    name: 'ポカポカハーブ',
    description:
      'ゲルド地方など 気温の高い場所で育つ薬草の一種 実や葉は辛味成分が強く 料理に使うと 寒さに強くなる効果を得る事ができる',
    locations: ['ゲルド砂漠', 'オルディン峡谷'],
    fuseAttackPower: 1,
    cookingEffect: '寒さガード',
  },
  {
    id: '239',
    category: 'materials',
    name: 'ビリビリハーブ',
    description:
      'ゲルド砂漠に多く自生している薬草の一種 電流を外へと逃がす特殊な繊維質を持ち 料理に使うと 電気への耐性を得る事ができる',
    locations: ['ゲルド砂漠', 'ハイラル丘陵'],
    fuseAttackPower: 1,
    cookingEffect: 'エレキガード',
  },
  {
    id: '240',
    category: 'materials',
    name: 'ゴーゴーニンジン',
    description:
      '村などでよく作られているニンジン 足腰を強くする効能があると言われており 調理して食べると 移動速度が上がる',
    locations: ['カカリコ村', 'ハテノ村'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '移動力アップ',
  },
  {
    id: '241',
    category: 'materials',
    name: 'ガッツニンジン',
    description:
      '薬草としても珍重されてきた 貴重なニンジン 活力の源となる成分を大量に含んでおり 調理すると がんばりゲージが限界を超えて増える',
    locations: ['東ハテール', 'ハイラル丘陵'],
    fuseAttackPower: 1,
    heartsRecoverable: 2,
    cookingEffect: 'MAXがんばり',
  },
  {
    id: '242',
    category: 'materials',
    name: 'ヨロイカボチャ',
    description:
      '食用として栽培される とても硬いカボチャ 料理に使うと カチコチ成分が効いて 防御力を かなり上げる効果がある',
    locations: ['カカリコ村', 'ハテノ村'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '防御アップ',
  },
  {
    id: '243',
    category: 'materials',
    name: 'ヒダマリカボチャ',
    description:
      'ハテノ村で作られている新種のカボチャ 太陽の光をたっぷり浴びて育ち 料理にすると 瘴気に蝕まれた身体を 治癒する効果が得られる',
    locations: ['ハテノ村'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.5,
    cookingEffect: '瘴気ダメージ回復',
  },
  {
    id: '244',
    category: 'materials',
    name: 'ゴーゴースミレ',
    description:
      '切り立った崖にも咲く 生命力豊かな花 料理に使うと 蓄えられた滋養成分によって 移動速度が上がる効果を得られる',
    locations: ['ヘブラ山脈', 'タバンタ辺境群'],
    fuseAttackPower: 1,
    cookingEffect: '移動力アップ',
  },
  {
    id: '245',
    category: 'materials',
    name: 'ツルギソウ',
    description:
      '葉や実にある鋭いトゲが特徴の薬草 一時的に筋力を増やす特殊な成分が含まれていて 料理に使うと 攻撃力が増える効果が発揮される',
    locations: ['東ハテール', 'フィローネ草原'],
    fuseAttackPower: 1,
    cookingEffect: '攻撃力アップ',
  },
  {
    id: '246',
    category: 'materials',
    name: 'ヨロイソウ',
    description:
      'たとえ踏まれてもおれない タフな薬草 その上部でしなやかな繊維質は 料理して食べると 体感を強化する効能があり 防御力が増す',
    locations: ['ハイラル丘陵', 'アッカレ高原'],
    fuseAttackPower: 1,
    cookingEffect: '防御アップ',
  },
  {
    id: '247',
    category: 'materials',
    name: 'しのび草',
    description:
      '主に森や草地に咲く花 夜になるとほのかに光を放つ 料理に使うと静けさを増やす効果が発揮される',
    locations: ['ハイラル大森林', '西ハテール'],
    fuseAttackPower: 1,
    cookingEffect: '静かさアップ',
  },
  {
    id: '248',
    category: 'materials',
    name: 'ヒダマリ草',
    description:
      '日当たりの良い 高空に生える野草 陽の光をたっぷり浴びて育った花弁は 料理すると 瘴気に蝕まれた身体を 治癒する効能がある',
    locations: ['ハイラル平原', 'オルディン峡谷'],
    fuseAttackPower: 1,
    cookingEffect: '瘴気ダメージ回復',
  },
  {
    id: '249',
    category: 'materials',
    name: 'アカリバナの種',
    description:
      '洞窟や井戸に生える アカリバナと呼ばれる花の種 衝撃を与えると即座に花開き その場に根を張る光は わずかに周囲を照らす',
    locations: ['ハイラルの洞窟'],
    fuseAttackPower: 1,
  },
  {
    id: '250',
    category: 'materials',
    name: '巨大なアカリバナの種',
    description:
      '洞窟で年月をかけて成長した アカリバナの種 衝撃を受けると その場に根を張り大きな花を開く とても明るい光で あたり一帯を照らす',
    locations: ['ハイラルの洞窟'],
    fuseAttackPower: 1,
  },
  {
    id: '251',
    category: 'materials',
    name: 'コンラン花',
    description:
      '強烈な臭いを放つ野生の花 この臭いをかぐと 前後不覚になり 一時的に味方と敵の区別がつかなくなるという',
    locations: ['ハイラルの地底'],
    fuseAttackPower: 1,
  },
  {
    id: '252',
    category: 'materials',
    name: 'バクダン花',
    description:
      '火薬によく似た成分を含んだ花 衝撃を与えたり 火をつけたりすると 周囲を巻き込んで爆発する',
    locations: ['ハイラルの洞窟', 'ハイラルの地底'],
    fuseAttackPower: 1,
  },
  {
    id: '253',
    category: 'materials',
    name: '姫しずか',
    description:
      'ハイラル王国の姫が愛したと言われる 可憐な花 以前より絶滅が危惧される種だが 近年 まれに自生しているのを見かける事ができる',
    locations: ['アッカレ高原', 'ハイラル丘陵'],
    fuseAttackPower: 1,
    cookingEffect: '静かさアップ',
  },
  {
    id: '254',
    category: 'materials',
    name: 'ガンバリバチのハチミツ',
    description:
      '巣から採れるハチミツは 栄養満点！ その高栄養価により 隠し味として使った料理は がんばりゲージ回復の効果を持つ',
    locations: ['ハイラル平原', '東ハテール'],
    fuseAttackPower: 1,
    heartsRecoverable: 2,
    cookingEffect: 'がんばり回復',
  },
  {
    id: '255',
    category: 'materials',
    name: 'ハイラルボックリ',
    description:
      'ハイラルに幅広く分布する樹木の実 油分を多く含んでおり 燃えやすく たき火にくべると火力が上がる',
    locations: ['ヘブラ山脈', 'ラネール大水源'],
    fuseAttackPower: 1,
  },
  {
    id: '256',
    category: 'materials',
    name: 'コログの葉',
    description:
      '何かが隠れていそうな 不思議な葉っぱ ちょっとした薬効成分がある 棒などに付けて うちわ代わりに使う事もできる',
    locations: ['ハイラル平原', 'ラネール大水源'],
    fuseAttackPower: 1,
    heartsRecoverable: 0.25,
  },
  {
    id: '257',
    category: 'materials',
    name: 'チュチュゼリー',
    description:
      'チュチュとそっくりなぷるぷるした固まり とても不安定な状態で 何か刺激を与えると変化するらしい',
    locations: ['ハイラル平原', '東ハテール'],
    fuseAttackPower: 1,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '258',
    category: 'materials',
    name: '赤チュチュゼリー',
    description:
      'ファイアチュチュにそっくりなぷるぷるした固まり 常に熱を発生していて 叩くと破裂して炎を発生する',
    locations: ['オルディン峡谷', 'オルディン山脈'],
    fuseAttackPower: 1,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '259',
    category: 'materials',
    name: '白チュチュゼリー',
    description:
      'アイスチュチュにそっくりな ぷるぷるした固まり 持ってみると ひんやりしてちょっと気持ちいい 叩くと破裂して冷気をまき散らす',
    locations: ['ヘブラ山脈', 'ゲルド高地'],
    fuseAttackPower: 1,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '260',
    category: 'materials',
    name: '黄チュチュゼリー',
    description:
      'エレキチュチュにそっくりな ぷるぷるした固まり しびれるほどではないが常にビリビリしている 叩くと破裂して周りに電気を発生させる',
    locations: ['西ハテール', 'ゲルド砂漠'],
    fuseAttackPower: 1,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '261',
    category: 'materials',
    name: 'キースの目玉',
    description:
      'ギョロギョロと辺りを見渡す 不気味な素材 矢に付けると 常に相手を見据える その瞳の力で狙った対象を追尾していく能力を与える',
    locations: ['ハイラル平原', '西ハテール'],
    fuseAttackPower: 1,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '262',
    category: 'materials',
    name: 'ファイアキースの目玉',
    description:
      'ファイアキースの熱気を帯びた目玉 薬の材料として重宝するほか 矢に付ける事で 命中率を上げる効能も得られる',
    locations: ['オルディン山脈', 'オルディン山脈 地底'],
    fuseAttackPower: 8,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '263',
    category: 'materials',
    name: 'アイスキースの目玉',
    description:
      'アイスキースの凍てつく目玉 一般的には薬の材料として使われるが 矢に付けると 相手に命中しやすくなる効果が得られる',
    locations: ['ヘブラ山脈', 'ラネール山'],
    fuseAttackPower: 4,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '264',
    category: 'materials',
    name: 'エレキースの目玉',
    description:
      'エレキースの電気を蓄えた目玉 薬の材料に使えるのはもちろんの事 矢に付ければ 目標に自分から向かう矢となる',
    locations: ['ゲルド砂漠', 'ゲルド砂漠 地底'],
    fuseAttackPower: 6,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '265',
    category: 'materials',
    name: 'ライクライクの胃石',
    description:
      'ライクライクの中から出てきた奇妙な丸石 体液が 結晶化してできた石で その成分は 薬の材料になることが知られている',
    locations: ['ハイラル平原', 'オルディン山脈'],
    fuseAttackPower: 4,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '266',
    category: 'materials',
    name: 'ファイアライクの胃石',
    description:
      '長くその高温の体内で 温められ続けた石 体外に取り出した後も 常に熱を帯びており その効能は 薬の材料としても重宝する',
    locations: ['オルディン山脈', 'オルディン山脈 地底'],
    fuseAttackPower: 12,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '267',
    category: 'materials',
    name: 'アイスライクの胃石',
    description:
      '非常に低温の体内で冷やされ続けた石 体外に取り出した後も 氷のように冷たい 虫と煮込んで 薬の材料にする事ができる',
    locations: ['ラネール山', 'ゲルド高地'],
    fuseAttackPower: 12,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '268',
    category: 'materials',
    name: 'エレクライクの胃石',
    description:
      'エレキライクの体内で高電圧に晒され続けた石 体外に取り出した後も わすかに帯電している 虫と煮込むと 薬の材料としても使う事ができる',
    locations: ['ハイラル平原', '東ハテール'],
    fuseAttackPower: 12,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '269',
    category: 'materials',
    name: 'カックーダの目玉',
    description:
      '動くものを常に視界の中心にとらえる目玉 虫と煮込むと 薬の材料として使えるほか 矢に付けて命中率を上げる効果も得られる',
    locations: ['ハイラル全土'],
    fuseAttackPower: 4,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '270',
    category: 'materials',
    name: 'ギブドの骨',
    description:
      '鋭い突起が複数ある 不気味な骨 武器に付けると攻撃力がかなり上がるが 不安定な形状のため すぐ壊れてしまう',
    locations: ['ゲルド砂漠', 'ゲルド砂漠 地底'],
    fuseAttackPower: 40,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '271',
    category: 'materials',
    name: 'ボコブリンの角',
    description:
      '鋭利な突起が複数ある角 武器に付けると攻撃力が上がる また 虫と煮込んで薬の材料にもできる',
    locations: ['ハイラル平原', '中央ハイラル 地底'],
    fuseAttackPower: 4,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '272',
    category: 'materials',
    name: '青ボコブリンの角',
    description:
      '外側が鋭利な二又の角 武器に付けると　二つの先端を同時に突き刺す形となるため　攻撃力がそこそこ上がる また 薬の材料にもなる',
    locations: ['ハイラル平原', 'オルディン峡谷'],
    fuseAttackPower: 7,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '273',
    category: 'materials',
    name: '黒ボコブリンの角',
    description:
      '先端が三叉状になった角 武器に付けて振ろうと 複数の刃で斬る形になり 攻撃力がかなり上がる また 煎じて虫と煮込む事で 薬の材料にもな',
    locations: ['グルド砂漠', 'ハイラル丘陵 地底'],
    fuseAttackPower: 17,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '274',
    category: 'materials',
    name: '白銀ボコブリンの角',
    description:
      '先端にユニークな装飾が付いた 大きな刃物上の角 見た目と裏腹に鋭く 武器に付けると攻撃力がすごく上がる 虫と煮込めば薬の材料にもなる',
    locations: ['不明'],
    fuseAttackPower: 31,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '275',
    category: 'materials',
    name: 'ボスボコブリンの角',
    description:
      '群れのリーダーの証である帯が巻かれた剣状の角。武器に付けて攻撃力を上げる事ができるほか、虫と煮込んで薬の材料にする事もできる',
    locations: ['ハイラル平原', 'ハイラル丘陵'],
    fuseAttackPower: 10,
    heartsRecoverable: 0,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '276',
    category: 'materials',
    name: '青ボスボコブリンの角',
    description:
      'リーダーを示す帯が巻かれた 斧状の角 武器に付けると攻撃力がそこそこ上がる また 虫と煮込めば薬を作る事もできる',
    locations: ['ハイラル平原', 'ラネール大水源'],
    fuseAttackPower: 16,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '277',
    category: 'materials',
    name: '黒ボスボコブリンの角',
    description:
      'リーダーの証の帯を2本もつ 両刃の斧状の角 武器に付ければ攻撃力がかなり上がる また 虫と煮込んで薬の材料にする事もできる',
    locations: ['ハイラル平原', '東ハテール'],
    fuseAttackPower: 27,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '278',
    category: 'materials',
    name: '白銀ボスボコブリンの角',
    description:
      '側面が鋭利な環状の角 丁寧に結ばれた帯は 魔力が宿っており 武器に付けると攻撃力が すごく上がる 虫と煮込めば薬の材料にもなる',
    locations: ['不明'],
    fuseAttackPower: 37,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '279',
    category: 'materials',
    name: 'モリブリンの角',
    description:
      '頭部の骨が変形してできた 硬い角 武器に付けると攻撃力が上がる また 虫と煮込む事で薬の材料にもなる',
    locations: ['ハイラル平原', '中央ハイラル 地底'],
    fuseAttackPower: 6,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '280',
    category: 'materials',
    name: '青モリブリンの角',
    description:
      '左右に大きく分かれ湾曲した角 先端が最も硬く 武器に付けると攻撃力がそこそこ上がる 煎じて虫と煮込めば 薬の材料にもなる',
    locations: ['ハイラル平原', 'オルディン峡谷'],
    fuseAttackPower: 13,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '281',
    category: 'materials',
    name: '黒モリブリンの角',
    description:
      '岩のように硬い突起が複数生えた角 重量があり 武器に付けると攻撃力がかなり上がる 煎じて虫と煮込めば 薬の材料としても使える',
    locations: ['ゲルド高地', '奥アッカレ'],
    fuseAttackPower: 24,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '282',
    category: 'materials',
    name: '白銀モリブリンの角',
    description:
      'らせん状にねじれた禍々しい角 岩以上の 硬さを誇り 武器に付けると攻撃力がすごく上がる 虫と一緒に煮込んで 薬の材料とする事もできる',
    locations: ['不明'],
    fuseAttackPower: 33,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '283',
    category: 'materials',
    name: 'リザルフォスの角',
    description:
      '薄く研ぎ澄まされたナイフ状の角 武器に付けると攻撃力を上げる事ができる また 虫と煮込めば 薬の材料にもなる',
    locations: ['ラネール湿原', 'ラネール大水源'],
    fuseAttackPower: 8,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '284',
    category: 'materials',
    name: '青リザルフォスの角',
    description:
      '天を突くように長く伸びた刀状の角 武器に付けると攻撃力がそこそこ上がる また 虫と煮込んで 薬の材料にする事もできる',
    locations: ['ラネール山', 'アッカレ高原 地底'],
    fuseAttackPower: 16,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '285',
    category: 'materials',
    name: '黒リザルフォスの角',
    description:
      '複数の切れ込みが入った刃物状の角 武器に付けると攻撃力がかなり上がる また 薬の材料として使う事もできる',
    locations: ['ゲルド砂漠', '東ハテール'],
    fuseAttackPower: 26,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '286',
    category: 'materials',
    name: '火吹きリザルフォスの角',
    description:
      '炎の力を蓄え 赤熱した角 虫と煮込むと 薬の材料になり 工夫次第で 蓄えた炎の力を引き出す事も可能',
    locations: ['オルディン峡谷', 'ゲルド高地'],
    fuseAttackPower: 15,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '287',
    category: 'materials',
    name: '氷吹きリザルフォスの角',
    description:
      '先端の結晶に凍てつく冷気の力を蓄えた角 虫と煮込むと 薬の材料になり 使い方次第で その冷気を利用する事もできる',
    locations: ['ヘブラ山脈', 'ゲルド高地'],
    fuseAttackPower: 15,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '288',
    category: 'materials',
    name: 'シビレリザルフォスの角',
    description:
      'ほとばしる稲妻に匹敵する電気を蓄積した角 虫と煮込めば 薬の材料として使えるほか 刺激を与えると放電する性質も利用価値がある',
    locations: ['ゲルド砂漠', 'フィローネ地方'],
    fuseAttackPower: 15,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '289',
    category: 'materials',
    name: '白銀リザルフォスの角',
    description:
      '触れるだけで何でも切り裂けそうな鎌状の角 武器に付けると 攻撃力がすごく上がる また 虫と煮込む事で 薬の材料にもなる',
    locations: ['不明'],
    fuseAttackPower: 34,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '290',
    category: 'materials',
    name: 'ホラブリンの角',
    description:
      '前後に伸びたハンマー状の角 前面が最も硬く 武器に付けると攻撃力が上がる 虫と一緒に煮込めば 薬の材料にする事もできる',
    locations: ['ハイラルの洞窟', 'オルディン峡谷 地底'],
    fuseAttackPower: 5,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '291',
    category: 'materials',
    name: '青ホラブリンの角',
    description:
      '成長してトゲが生えたハンマー状の角 武器に付けると攻撃力がそこそこ上がる また 虫と煮込めば 薬の材料にもなる',
    locations: ['デスマウンテン', 'デスマウンテン 地底'],
    fuseAttackPower: 11,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '292',
    category: 'materials',
    name: '黒ホラブリンの角',
    description:
      '時間をかけて大きく重く育った ハンマー状の角 武器に付けると攻撃力がかなり上がる 虫と一緒に煮込めば 薬の材料にもなる',
    locations: ['ハイラルの洞窟', 'ゲルド砂漠 地底'],
    fuseAttackPower: 22,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '293',
    category: 'materials',
    name: '白銀ホラブリンの角',
    description:
      '先端が非常に硬い 前後に湾曲した形状の角 武器に付けると攻撃力がすごく上がる 煎じて虫と煮込めば 薬の材料にする事もできる',
    locations: ['不明'],
    fuseAttackPower: 32,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '294',
    category: 'materials',
    name: 'ライネルの刃角',
    description:
      'ライネルの双角の片方である刃物状の角 非常に鋭く 武器に付けると攻撃力が上がる また 虫と煮込めば薬の材料にもなる',
    locations: ['ハイラル平原', '中央ハイラル 地底'],
    fuseAttackPower: 22,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '295',
    category: 'materials',
    name: 'ライネルの砕角',
    description:
      'ライネルの双角の片方 爪のように生えた突起は かなりの硬さで 武器に付けると攻撃力が上がり 虫と煮込めば薬の材料にする事もできる',
    locations: ['ハイラル平原', '中央ハイラル 地底'],
    fuseAttackPower: 18,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '296',
    category: 'materials',
    name: '青髪ライネルの刃角',
    description:
      '青髪のライネルの双角の片方 全体が鋭い刃物状で 武器に付けると攻撃力がそこそこ上がる 虫と煮込んで薬の材料にする事もできる',
    locations: ['ラネール大水源', 'オルディン峡谷 地底'],
    fuseAttackPower: 33,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '297',
    category: 'materials',
    name: '青髪ライネルの砕角',
    description:
      '青髪のライネルの双角の片方 枝分かれした先端は 岩のような硬さで 武器に付けると攻撃力が そこそこ上がる また 薬の材料にもなる',
    locations: ['ラネール大水源', 'オルディン峡谷 地底'],
    fuseAttackPower: 29,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '298',
    category: 'materials',
    name: '白髪ライネルの刃角',
    description:
      '白髪のライネルの双角の片方 連なる刃物の形状が 触れた物を切り裂き 武器に付けるとかなり 攻撃力が上がる 虫と煮込めば薬の材料にもなる',
    locations: ['フィローネ草原 地底', '中央ハイラル 地底'],
    fuseAttackPower: 44,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '299',
    category: 'materials',
    name: '白髪ライネルの砕角',
    description:
      '白髪のライネルの双角の片方 爪のような形状の 先端部分は非常に硬く 武器に付けると攻撃力が かなり上がる 虫と一緒に煮込めば薬にもなる',
    locations: ['フィローネ草原 地底', '中央ハイラル 地底'],
    fuseAttackPower: 40,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '300',
    category: 'materials',
    name: '白銀ライネルの刃角',
    description:
      '極限まで研ぎ澄まされた 長く鋭い角 切れ味は 申し分なく 武器に付けると攻撃力がすごく上がる 煎じて虫と煮込めば 薬の材料としても使える',
    locations: ['不明'],
    fuseAttackPower: 55,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '301',
    category: 'materials',
    name: '白銀ライネルの砕角',
    description:
      '白銀のライネルの双角の片方 ダイヤモンド並の 硬度を誇り 武器に付けると攻撃力がすごく上がる 薬の材料としても非常に貴重',
    locations: ['不明'],
    fuseAttackPower: 51,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '302',
    category: 'materials',
    name: '兵隊ゴーレムの角',
    description:
      '兵隊ゴーレムの頭部にある 刃物状の角 とても鋭いため 取り扱うには注意が必要だ',
    locations: ['始まりの空島', '北ゲルド空諸島'],
    fuseAttackPower: 3,
    cookingEffect: '',
  },
  {
    id: '303',
    category: 'materials',
    name: '兵隊ゴーレムの角(中等)',
    description:
      '兵隊ゴーレム(中等)の頭部にある ナタのような角 小枝の伐採や 草花の刈り取りに向いた形状で 武器に付けると 攻撃力がそこそこ上がる',
    locations: ['ヘブラ山脈', '天へと連なる島々'],
    fuseAttackPower: 8,
    cookingEffect: '',
  },
  {
    id: '304',
    category: 'materials',
    name: '兵隊ゴーレムの角(上等)',
    description:
      '兵隊ゴーレム(上等)の頭部にある ノコギリ状の角 武器に付けると 攻撃力がかなり上がり 草花だけではなく 大きな樹木の伐採にも役立つ',
    locations: ['ラネール空諸島', '雷鳴の島'],
    fuseAttackPower: 18,
    cookingEffect: '',
  },
  {
    id: '305',
    category: 'materials',
    name: '兵隊ゴーレムの角(特等)',
    description:
      '鋭い刃を持つ 円盤が付いた角 円盤部分は 不思議な力で回転し 触れた物を 切断する 武器に付けるとすごく攻撃力が上がる',
    locations: ['不明'],
    fuseAttackPower: 24,
    cookingEffect: '',
  },
  {
    id: '306',
    category: 'materials',
    name: '隊長ゴーレムの角',
    description:
      '隊長ゴーレムの頭部にある 波打つ両刃状の角 鋭利で 刃物の代わりに使うには申し分なく 武器に付けると攻撃力を上げる事ができる',
    locations: ['始まりの空島', '天へと連なる島々'],
    fuseAttackPower: 5,
    cookingEffect: '',
  },
  {
    id: '307',
    category: 'materials',
    name: '隊長ゴーレムの角(中等)',
    description:
      '先端が左右に分かれ 鉤状になった鋭い角 触れるものを 簡単に切り裂く威力をもつ 武器に付けると 攻撃力がそこそこ上がる',
    locations: ['ラネール空諸島', '西ハテール'],
    fuseAttackPower: 15,
    cookingEffect: '',
  },
  {
    id: '308',
    category: 'materials',
    name: '隊長ゴーレムの角(上等)',
    description:
      '先端が まるで装飾されたような 複雑な形状をした 鋭利な刃物状の角 武器に付けると 攻撃力がかなり上がる',
    locations: ['ドイブラン遺跡', 'ラネール空諸島'],
    fuseAttackPower: 25,
    cookingEffect: '',
  },
  {
    id: '309',
    category: 'materials',
    name: '隊長ゴーレムの角(特等)',
    description:
      '根元から二つに分かれた 刃物状の角 先端や突起は非常に斬れ味が鋭く 武器に付けると 攻撃力がすごく上がる',
    locations: ['不明'],
    fuseAttackPower: 35,
    cookingEffect: '',
  },
  {
    id: '310',
    category: 'materials',
    name: 'ヒノックスの角',
    description:
      '周囲を トゲ付き板で覆った角 武器に付けると攻撃力が上がる 角本体を 虫と煮込めば 薬の材料にもなる',
    locations: ['ハイラル丘陵', '西ハテール'],
    fuseAttackPower: 12,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '311',
    category: 'materials',
    name: '青ヒノックスの角',
    description:
      '硬い鎖を巻き付けた 禍々しい角 武器に付けると 攻撃力がそこそこ上がり また 虫と煮込んで 薬の材料にする事もできる',
    locations: ['東ハテール 地底', '西ハテール'],
    fuseAttackPower: 19,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '312',
    category: 'materials',
    name: '黒ヒノックスの角',
    description:
      '潰した廃材を硬く巻き付けた角 武器に付けた時 振り回しやすい形状で 攻撃力がかなり上がる また 虫と煮込めば 薬の材料にする事もできる',
    locations: ['東ハテール', '西ハテール 地底'],
    fuseAttackPower: 27,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '313',
    category: 'materials',
    name: 'スタルヒノックスの角',
    description:
      '不気味な骨が突き刺さった トゲトゲが痛そうな角 武器に付けると攻撃力がすごく上がる 虫と煮込んで 薬の材料に使う事もできる',
    locations: ['東ハテール', '中央ハイラル 地底'],
    fuseAttackPower: 29,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '314',
    category: 'materials',
    name: 'モルドラジークのアゴ骨',
    description:
      '砂をかき分けて進む際 役に立つ大きく堅牢な骨 非常に硬く武器に付けると攻撃力が かなり上がり 煎じて虫と煮込めば薬にもなる',
    locations: ['ゲルド砂漠'],
    fuseAttackPower: 32,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '315',
    category: 'materials',
    name: 'グリオークの火炎角',
    description:
      '炎をまとったグリオークの 頭部にある冠状の角 刺激によって火を放ち 武器に付けると攻撃力が すごく上がる 煎じれば薬の材料にもなる',
    locations: ['オルディン峡谷', 'ハイリア湖'],
    fuseAttackPower: 30,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '316',
    category: 'materials',
    name: 'グリオークの氷雪角',
    description:
      '冷気を操るグリオークの冠状の角 凍えるほど 冷たい刃を備えており 武器に付けると攻撃力が すごく上がる 虫と煮込んで薬の材料にもできる',
    locations: ['ゲルド高地', 'ヘブラ山脈'],
    fuseAttackPower: 30,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '317',
    category: 'materials',
    name: 'グリオークの雷電角',
    description:
      '雷を帯びたグリオークの 頭部にある冠状の角 溜めた電気を放電する性質があり 武器に付けると 攻撃力がすごく上がる 煮込めば薬の材料にもなる',
    locations: ['ハイラル平原', 'フィローネ草原'],
    fuseAttackPower: 30,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '318',
    category: 'materials',
    name: 'デグガーマの大牙',
    description:
      '鉱石を削るために用いる 巨大な牙 武器に付けると攻撃力がそこそこ上がる 虫と煮込む事で 薬の材料にもなる',
    locations: ['ゲルド高地 地底', '中央ハイラル 地底'],
    fuseAttackPower: 14,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '319',
    category: 'materials',
    name: '黒曜デグガーマの大牙',
    description:
      '鉱石に打ち付けて粉砕するための 巨大な牙 武器に付けると攻撃力がかなり上がる 煎じて虫と煮込めば 薬を作る事ができる',
    locations: ['ゲルド砂漠 地底', 'ハイラル丘陵 地底'],
    fuseAttackPower: 24,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '320',
    category: 'materials',
    name: '白蒼デグガーマの大牙',
    description:
      '硬い岩盤をものともせず掘り進むための 巨大な牙 武器に付けると攻撃力がすごく上がる 虫と一緒に煮込めば 薬の材料にする事もできる',
    locations: ['ヘブラ山脈 地底', 'タバンタ辺境 地底'],
    fuseAttackPower: 35,
    cookingEffect: '効果時間アップ +00:40',
  },
  {
    id: '321',
    category: 'materials',
    name: 'オルドラの角',
    description:
      '赤き精霊オルドラの鋭利な角 炎の力が結晶化して 角になったと言われている 刃物状で 武器に付けると攻撃力がすごく上がる',
    locations: ['不明'],
    fuseAttackPower: 26,
    cookingEffect: '効果時間アップ +30:00',
  },
  {
    id: '322',
    category: 'materials',
    name: 'オルドラの龍岩石',
    description:
      'オルドラの背中から採れる 非常に硬い岩石 武器に付けると 多くの物を砕く事ができ 同時に炎を発生させる性質がある',
    locations: ['不明'],
    fuseAttackPower: 16,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '323',
    category: 'materials',
    name: 'ネルドラの角',
    description:
      '青き精霊ネルドラの鋭利な角 氷の力が結晶化して 角になったと言われている 刃物状で 武器に付けると攻撃力がすごく上がる',
    locations: ['不明'],
    fuseAttackPower: 26,
    cookingEffect: '効果時間アップ +30:00',
  },
  {
    id: '324',
    category: 'materials',
    name: 'ネルドラの龍岩石',
    description:
      'ネルドラの背中から採れる 非常に硬い岩石 武器に付けると 多くの物を砕く事ができ 同時に氷を発生させる性質がある',
    locations: ['不明'],
    fuseAttackPower: 16,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '325',
    category: 'materials',
    name: 'フロドラの角',
    description:
      '黄金の精霊フロドラの鋭利な角 雷の力が結晶化して 角になったと言われている 刃物状で 武器に付けると攻撃力がすごく上がる',
    locations: ['不明'],
    fuseAttackPower: 26,
    cookingEffect: '効果時間アップ +30:00',
  },
  {
    id: '326',
    category: 'materials',
    name: 'フロドラの龍岩石',
    description:
      'フロドラの背中から採れる 非常に硬い岩石 武器に付けると 多くの物を砕く事ができ 同時に電気を発生させる性質がある',
    locations: ['不明'],
    fuseAttackPower: 16,
    cookingEffect: '効果時間アップ +01:20',
  },
  {
    id: '327',
    category: 'materials',
    name: '白龍の角',
    description:
      '白龍から欠け落ちた 角 優しく光っていて 見ていると気持ちが落ち着く 武器に付けると 使用者を癒す不思議な性質がある',
    locations: ['不明'],
    fuseAttackPower: 20,
    cookingEffect: '効果時間アップ +30:00',
  },
  {
    id: '328',
    category: 'materials',
    name: '白龍の龍岩石',
    description:
      '白龍の背中から採れる 非常に硬い岩石 武器に付けると 多くの物を砕く事ができ 同時に使用者を癒す 不思議な性質がある',
    locations: ['不明'],
    fuseAttackPower: 12,
    cookingEffect: '効果時間アップ +01:20',
  },
];
